type Product {
  id: Int!
  title: String!
  description: String
  content: String
  indexImage: String
  slug: String!
  price: Int!
  stock: Int!
}

input CreateProductInput {
  title: String!
  description: String
  content: String
  indexImage: String
  slug: String
  price: Int!
  stock: Int!
}

input UpdateProductInput {
  id: Int!
  title: String
  description: String
  content: String
  indexImage: String
  slug: String
  price: Int
  stock: Int
}